// components/Footer.vue
<template>
<div class="px-12 py-4 mt-24 bg-background-card rounded-t-3xl">
  <v-footer color="#16373C">
    <div>
      <div class="flex items-center cursor-pointer">
        <img src="@/assets/CorvusLogo.svg" width="50px" />
        <div class="text-white-hex font-bold text-xl mx-2">Corvus Aosp</div>
      </div>
    </div>
    <v-spacer></v-spacer>
    <div>
      <div class="flex">
        <img class="mx-2 cursor-pointer" src="@/static/Gpay.svg" width="50px" />
        <img class="mx-2 cursor-pointer" src="@/static/Paypal.svg" width="40px" />
        <img class="mx-2 cursor-pointer" src="@/assets/Github.svg" width="50px" />
        <img class="mx-2 cursor-pointer" src="@/assets/Telegram.svg" width="50px" />
      </div>
    </div>
  </v-footer>
</div>
</template>
<style scoped>
</style>

// src/lib/footer.svelte
<main class="bg-light-black py-8 px-32 rounded-lg flex justify-between items-center">
	<div class="flex gap-4 items-center">
		<img src="https://ik.imagekit.io/corvus/Corvus_Logo.svg" alt="Corvus Logo" width="50px" />
		<span class="font-extrabold text-2xl">Corvus-Aosp</span>
	</div>
	<div class="flex gap-2">
        <img src="https://ik.imagekit.io/corvus/Vector.svg" width="50px" alt="Corvus Logo" />
        <img src="https://ik.imagekit.io/corvus/Gpay.svg" width="50px" alt="Corvus Logo" />
        <img src="https://ik.imagekit.io/corvus/Paypal.svg" width="43px" alt="Corvus Logo" />
        <img src="https://ik.imagekit.io/corvus/Github.svg" width="50px" alt="Corvus Logo" />
    </div>
</main>
