// src/lib/header.svelte
<main>
	<div
		class="flex lg:flex-row item-center rounded-lg flex-col gap-2 w-full fixed top-0 left-0 justify-between lg:px-24 lg:py-8 py-4 items-center"
		style="backdrop-filter: blur(10px); background-color: rgba(33, 33, 43, 0.5);"
	>
		<div class="flex gap-4 items-center">
			<img src="https://ik.imagekit.io/corvus/Corvus_Logo.svg" alt="Corvus Logo" width="50px" />
			<h1 class="font-extrabold text-4xl cursor-pointer">Corvus-Aosp</h1>
		</div>
		<div class="flex justify-evenly font-semibold items-center gap-2 lg:gap-16">
			<div class="header">Specials</div>
			<div class="header">Screenshots</div>
			<div class="header">Team</div>
			<button class="lg:px-4 lg:py-2 px-2 py-1 bg-primary rounded-lg text-sm lg:text-lg"
				>What's New</button
			>
		</div>
	</div>
</main>

<style>
	.header {
		color: #f4f0ff;
		cursor: pointer;
		padding: 0.25rem 0.25rem;
		border-radius: 0.5rem;
	}
	.header:hover {
		color: #7d6df8;
		cursor: pointer;
		background-color: #7e7efc41;
		padding: 0.25rem 0.25rem;
	}
</style>

// components/Header.vue
<template>
  <v-app-bar color="rgba(0, 0, 0, 0)" class="px-12 py-6" fixed flat rounded>
    <div class="flex flex-column items-center justify-evenly px-6">
        <div class="flex flex-column items-center cursor-pointer">
            <img src="@/assets/CorvusLogo.svg" width="50px" />
            <div class="text-white-hex font-bold text-xl mx-2">Corvus Aosp</div>
        </div>
        <div>
            <button class="bg-white-hex text-primary font-bold text-xl p-2 mx-2 rounded-lg">Download</button>
            <button class="bg-white-hex text-primary font-bold text-xl p-2 mx-2 rounded-lg">What's New!</button>
        </div>
    </div>
  </v-app-bar>
</template>

<script>
export default {
mounted() {
    window.onscroll = () => {
      this.changeColor();
    };
  },
  methods: {
    changeColor() {
      if (
        document.body.scrollTop > 100 ||
        document.documentElement.scrollTop > 100
      ) {
        this.bg = 'white';
      } else {
        this.bg = 'transparent';
      }
    },
  },

}
</script>

<style>

</style>
